PRAGMA encoding = 'UTF-8';

-- Les personnes :
INSERT INTO personne(pers_id, pers_nom, pers_prenom, pers_autre_nom, pers_naissance, pers_mort, pers_titre, pers_fonction, pers_image, pers_url, pers_description) VALUES
(1, "Adhémar de Monteil de Grignan", "Joseph", "chevalier de Grignan", NULL, NULL, NULL, NULL, NULL, NULL, "Sans doute le frère de François Adhémar de Monteil, comte de Grignan, époux de Françoise de Sévigné."),
(2, "Barbeyrac", "Charles de", NULL, "1629", "1699", NULL, "Médecin", NULL, "https://data.bnf.fr/fr/12534745/charles_de_barbeyrac/", NULL),
(3, "Bauves-Contenant", "Marguerite de", NULL, "1630?", "1701", "comtesse de Brinon", NULL, NULL, NULL, NULL),
(4, "Beuzelin de Bosmelet", "Anne-Marie", NULL, "1668?", "1752", NULL, NULL, NULL, NULL, NULL),
(5, "Boucher d'Orsay", "Marguerite", NULL, NULL, NULL, "marquise de Montchevreuil", NULL, NULL, NULL, NULL),
(6, "Bourbon", "Louis de", "Louis XIV", "1638", "1715", "Roi de France", NULL, NULL, "https://data.bnf.fr/fr/11913463/louis_14/", NULL),
(7, "Bourbon", "Louis de", "Monseigneur, Grand Dauphin", "1666", "1711", "Dauphin de France", NULL, NULL, "https://data.bnf.fr/fr/12510194/louis/", NULL),
(8, "Brinon-Senneterre", "Marie-Madeleine de", NULL, "1673", "1716", NULL, NULL, NULL, NULL, NULL),
(9, "Colbert", "Pierre-Gilbert", NULL, "1671?", "1733", "marquis de Villacerf", NULL, NULL, NULL, NULL),
(10, "Coulanges", "Philippe-Emmanuel de", NULL, "1633", "1716", "marquis de Coulanges", "Magistrat, chansonnier et homme de lettres", 1, "https://fr.wikipedia.org/wiki/Philippe-Emmanuel_de_Coulanges", "Cousin et ami de la marquise de Sévigné. Conseiller au Parlement de Metz puis de Paris. Auteur de chanson."),
(11, "Créquy", "Madeleine de", NULL, "1662", "1707", "duchesse de la Trémoille", NULL, NULL, NULL, NULL),
(12, "Damas de Thianges", "Diane-Gabrielle de", NULL, "1656", "1715", "duchesse de Nevers", NULL, NULL, "https://data.bnf.fr/13003675/diane-gabrielle_de_damas_de_thianges_nevers/", NULL),
(13, "Durfort", "Geneviève-Marie de", NULL, "1680?", "1740?", "duchesse de Lauzun", NULL, NULL, NULL, "Elle épouse en 1695, à l'âge de 15 ans, le duc de Lauzun alors âgé de 62 ans."),
(14, "Durfort de Lorges", "Marie-Gabrielle de", NULL, "1678", "1743", "duchesse de Saint-Simon", NULL, NULL, NULL, "Epouse de Louis de Rouvroy, duc de Saint-Simon."),
(15, "Frémont", "Marie? de", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Epouse de Jacques Rioult de Douilly ; fille de Nicolas de Frémont ; soeur de Geneviève Frémont d'Auneuil."),
(16, "Frémont d'Auneuil", "Geneviève", "Maréchale de Lorges", "1659?", "1727", "comtesse de Lorges, duchesse de Quintin", NULL, NULL, NULL, "Epouse depuis 1676 de Guy de Durfort, maréchal, comte puis duc de Lorges-Quintin"),
(17, "Goyon-Matignon", "Catherine Thérèse de", "madame de Seignelay", "1661?", "1700?", "comtesse de Marsan", NULL, NULL, NULL, "Madame de Marsan était précédemment mariée à Jean-Baptiste Antoine Colbert, marquis de Seignelay, avant d'épouser en seconde noce Charles de Lorraine, comte de Marsan."),
(18, "Grignan", "Pauline de", NULL, "1674", "1737", "marquise de Simiane", NULL, 1, "https://data.bnf.fr/fr/12002277/pauline_de_grignan_simiane/", "Petite-fille de la marquise de Sévigné. Dame de compagnie de la duchesse d’Orléans. Elle dirige une première édition tronquée de la correspondance entre Madame de Sévigné et Madame de Grignan."),
(19, "Gué de Bagnols", "Michelle-Gabrielle du", NULL, "1673?", "1756", NULL, NULL, NULL, NULL, "Elle épouse finalement Jacques-Tannegui Le Veneur, comte de Tillières."),
(20, "Gué de Bagnols", "Marie-Angélique du", NULL, "1641", "1723", NULL, NULL, NULL, "https://data.bnf.fr/fr/14456521/marie_angelique_de_coulanges/", "Femme de lettres, amie proche de madame de Sévigné."),
(21, "Hamilton", "Richard", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(22, "L'Hôpital", "de", NULL, NULL, NULL, NULL, NULL, NULL, NULL, "Peut-être Guillaume François Antoine, marquis de L'Hôpital"),
(23, "La Ferté-Senneterre", "Louis de", NULL, "1659", "1732", NULL, "Prédicateur jésuite", 1, NULL, NULL),
(24, "La Guiche", "Bernard de", NULL, "1642", "1696", "comte de Saint-Géran", "Général, Ambassadeur", NULL, "https://data.bnf.fr/fr/14974106/bernard_de_la_guiche/", "Ambassadeur à Florence, en Angleterre et dans le Brandebourg."),
(25, "La Tour d'Auvergne", "Emmanuel-Théodose de", NULL, "1668", "1730", "duc d'Albret, duc de Bouillon", "Grand chambellan de France", NULL, NULL, "A ne pas confondre avec le cardinal de Bouillon."),
(26, "La Tour d’Auvergne", "Emmanuel-Théodose de", "Cardinal de Bouillon", "1643", "1715", "Cardinal-prêtre", "Cardinal, abbé, grand aumônier", 1, "https://data.bnf.fr/fr/10742003/emmanuel_theodose_de_la_tour_d_auvergne_bouillon/", "Docteur en théologie, cardinal (1669), grand aumônier de France (1671). Abbé de Saint-Martin de Pontoise et de Cluny. Obtient la faveur de Louis XIV avant de tomber en disgrâce en 1685 pour avoir rédigé une satire contre le gouvernement et le Roi. Ambassadeur de France à Rome (1698)."),
(27, "La Tour d'Auvergne", "Henri-Oswald de", "Abbé d'Auvergne", "1670", "1747", "Cardinal-prêtre", "Cardinal, archevêque", NULL, "https://data.bnf.fr/fr/16296239/henri_oswald_de_la_tour_d_auvergne_albret/", NULL),
(28, "La Tour d'Auvergne", "Frédéric-Jules de", "Prince d\'Auvergne", "1672", "1733", "chevalier de Bouillon", NULL, NULL, NULL, "Grand-Croix de l'ordre de Malte (1690), proche du Grand Dauphin qui le nomme capitaine de vaisseau, libertin."),
(29, "La Trémoille", "Marie-Armande de", NULL, "1677", "1717", "Princesse de Turenne, duchesse d'Albret", NULL, 1, NULL, NULL),
(30, "La Trémoille", "Marie-Anne de", NULL, "1676", "1708", "marquise de Royan", NULL, NULL, NULL, NULL),
(31, "Lamoignon", "Chrétien-François de", NULL, "1644", "1709", "marquis de Basville", NULL, NULL, "https://data.bnf.fr/fr/16096096/chretien-francois_de_lamoignon/", "Fils aîné de Guillaume de Lamoignon (1617-1677). Conseiller au Parlement de Paris (1666), maître des requêtes (1671), avocat général (1674), président à mortier (1698)."),
(32, "Le Coigneux", NULL, "Présidente Le Coigneux", NULL, NULL, NULL, NULL, NULL, NULL, "Peut-être l'épouse de François Le Coigneux Bachaumont."),
(33, "Le Tellier Louvois", "Marguerite", NULL, "1679?", "1711", "duchesse de Villeroy", NULL, NULL, NULL, "Marguerite Le Tellier Louvois se marie en 1694 avec Louis Nicolas de Neufville de Villeroy. La même année, ce dernier reçoit par transmission du vivant de son père (François de Neufville de Villeroy) le titre de duc de Villeroy. Son épouse devient donc duchesse de Villeroy à la place de sa mère, Marie-Marguerite de Cossé-Brissac. Cependant, l'habitude pousse peut-être les contemporains à continuer à nommer Marie-Marguerite de Cossé-Brissac 'duchesse de Villeroy'."),
(34, "Longueuil", "Claude de", NULL, "1668", "1715", "marquis de Poissy", NULL, NULL, NULL, "Il épouse en 1698 en seconde noce Charlotte-Roque de Varangeville"),
(35, "Lorraine", "Charles de", NULL, "1648", "1708", "comte de Marsan", NULL, NULL, NULL, NULL),
(36, "Mancini-Mazarini", "Philippe-Julien", NULL, "1641", "1707", "duc de Nevers", NULL, NULL, "https://data.bnf.fr/fr/14811880/philippe-julien_mancini-mazarini_nevers/", "Neveu du cardinal Mazarin."),
(37, "Marillac", "René de", NULL, "1639", "1719", "Seigneur d'Ollainville", "Conseiller au Parlement", NULL, NULL, "Conseiller au Parlement de Paris, avocat général (1663), maître des requêtes (1671), intendant du Poitou (1673) puis de Normandie (1684), conseiller d'Etat (1686). Il organise des dragonnades dans le Poitou à partir de 1681."),
(38, "Montmorency", "Charles François Frédéric de", NULL, "1662", "1726", "duc de Piney-Luxembourg", NULL, NULL, NULL, NULL),
(39, "Montmorency-Luxembourg", "Paul Sigismond de", NULL, "1664", "1731", "duc de Châtillon, comte de Luxe", "Colonel, brigadier, lieutenant-général", NULL, "https://data.bnf.fr/fr/16987206/paul-sigismond_de_montmorency-luxembourg/", "Participe à la bataille de Fleurus (1690), au siège de Mons (1691), au siège de Namur (1692), à la bataille de Steinkerque (1692) et à la bataille de Neerwinden (1693)."),
(40, "Mornay-Montchevreuil", "Catherine-Françoise de", NULL, "1678?", "1729", NULL, NULL, NULL, NULL, NULL),
(41, "Moulceau", "Philippe", "Président de Moulceau", NULL, NULL, NULL, "Magistrat à la Cour des comptes de Montpellier", NULL, NULL, "Proche des époux de Grignan. Peu évoqué par la marquise de Sévigné."),
(42, "Nompar de Caumont", "Henri-Jacques", NULL, "1675", "1726", "duc de La Force", NULL, NULL, "https://data.bnf.fr/fr/10730619/henri-jacques_nompar_de_caumont_la_force/", "Elu en 1715 à l'Académie française."),
(43, "Nompar de Caumont", "Antonin", NULL, "1633", "1723", "duc de Lauzun", "Capitaine des Gardes du corps du Roi", NULL, "https://data.bnf.fr/fr/12098262/antonin_nompar_de_caumont_lauzun/", "Militaire et courtisan, chevalier de l'ordre de la Jarretière."),
(44, "Pracontal", "Jeanne-Ursule de", NULL, NULL, "1744", "comtesse de Busseaux", NULL, NULL, NULL, "Elle est décédée à environ 100 ans."),
(45, "Pracontal", "Armand de", NULL, NULL, "1703", NULL, "Maréchal de camp, lieutenant-général, gouverneur", NULL, NULL, "Gouverneur de Menin, chevalier de Saint-Louis."),
(46, "Rabutin-Chantal", "Marie de", "Madame de Sévigné", "1626", "1696", "marquise de Sévigné", NULL, 1, "https://data.bnf.fr/fr/11924578/marie_de_rabutin-chantal_sevigne/", "Femme d’esprit, elle fait partie du monde galant parisien, fréquentant Mlle de Scudéry et la jeune comtesse de Lafayette. Veuve depuis ses 25 ans, elle a deux enfants dont une fille, Françoise-Marguerite, qu’elle couve de son amour. Le départ de cette dernière en Provence en 1671 est un crève-cœur pour elle. Elles entament alors une correspondance qui dure plusieurs décennies. Jusqu’à la fin de ses jours, la marquise partage son temps entre son hôtel Carnavalet à Paris, son château en Bretagne et le palais de Grignan où réside sa fille."),
(47, "Rioult de Douilly", "Marie-Geneviève", NULL, "1673?", "1751", "marquise de Saint-Hérem", NULL, NULL, NULL, "Elle épouse Charles-Louis de Montmorin-Saint-Hérem le 6 février 1696."),
(48, "Saint-Gelais de Lansac", "Anne Armande de", NULL, "1637", "1709", "duchesse de Créquy", NULL, NULL, NULL, NULL),
(49, "Senneterre", "Jean-Charles de", NULL, "1608", "1696", "comte de Brinon", NULL, NULL, NULL, NULL),
(50, "Souvré", "Anne de", NULL, "1655", "1727", "marquise de Louvois", NULL, NULL, NULL, "Epouse du ministre Francois-Michel Le Tellier Louvois ?"),
(51, "Sévigné", "Françoise-Marguerite de", NULL, "1646", "1705", "comtesse de Grignan", NULL, 1, "https://data.bnf.fr/fr/12002273/francoise-marguerite_de_sevigne_grignan/", "Fille de la marquise de Sévigné. Principale destinataire de ses lettres."),
(52, "Testu de Belval", "Jacques", NULL, "1626?", "1706", NULL, "Abbé", NULL, "https://data.bnf.fr/fr/12918608/jacques_testu/", NULL),
(53, "Vienne", "Elisabeth de", NULL, "1607", "1696", "comtesse de Bouteville", NULL, NULL, NULL, NULL);

-- Les lieux :
INSERT INTO lieu(lieu_id, lieu_nom, lieu_ville, lieu_dpt, lieu_latitude, lieu_longitude, lieu_url, lieu_description) VALUES
(1, "Abbaye de Saint-Martin", "Pontoise", "Val d’Oise", 49.042385, 2.093165, "https://catalogue.bnf.fr/ark:/12148/cb12507777h", "Palais abbatial et ses jardins construits par le cardinal de Bouillon à Pontoise. Détruite à la fin du XVIIIe siècle."),
(2, "Château de Grignan", "Grignan", "Drôme", 44.418791, 4.909030, "https://www.pop.culture.gouv.fr/notice/merimee/PA00116961", "Château appartenant à la fille de la marquise de Sévigné et son mari. La marquise y meurt en 1696."),
(3, "Hôtel de Carnavalet", "Paris", "Paris", 48.857343, 2.362628, "https://www.pop.culture.gouv.fr/notice/merimee/PA00086125", "Hôtel du Marais habité par la marquise de Sévigné de 1677 à 1696. Actuel Musée Carnavalet."),
(4, "Hôtel de Coulanges", "Paris", "Paris", 48.855663, 2.365564, "https://www.pop.culture.gouv.fr/notice/merimee/PA00086286", "Résidence du marquis de Coulanges située place des Vosges. La marquise de Sévigné y vit quelques années jusqu’à son mariage.");

-- Les lettres :
INSERT INTO lettre(lettre_id, lettre_date, lettre_lieu, lettre_expediteur, lettre_destinataire) VALUES
(1, "6 février 1671", "Paris", "Madame de Sévigné", "Madame de Grignan"),
(2, "4 février 1696", "Grignan", "Madame de Sévigné", "Président de Moulceau"),
(3, "17 février 1696", "Saint-Martin", "Monsieur de Coulanges (et Cardinal de Bouillon)", "Madame de Sévigné"),
(4, "20 février 1696", "Paris", "Monsieur de Coulanges", "Mesdames de Sévigné et de Grignan"),
(5, "27 février 1696", "Paris", "Monsieur de Coulanges", "Madame de Simiane"),
(6, "29 mars 1696", "Grignan", "Madame de Sévigné", "Monsieur de Coulanges");

-- Les citations :
INSERT INTO citeP(citeP_lettre_id, citeP_pers_id) VALUES
(1, 46),
(1, 51),
(2, 41),
(2, 46),
(2, 51),
(3, 5),
(3, 10),
(3, 13),
(3, 14),
(3, 15),
(3, 16),
(3, 18),
(3, 19),
(3, 21),
(3, 22),
(3, 25),
(3, 26),
(3, 29),
(3, 32),
(3, 33),
(3, 34),
(3, 40),
(3, 44),
(3, 46),
(3, 47),
(3, 48),
(3, 51),
(4, 3),
(4, 3),
(4, 8),
(4, 9),
(4, 10),
(4, 17),
(4, 18),
(4, 19),
(4, 26),
(4, 29),
(4, 30),
(4, 33),
(4, 34),
(4, 35),
(4, 38),
(4, 39),
(4, 42),
(4, 49),
(4, 50),
(5, 1),
(5, 6),
(5, 7),
(5, 10),
(5, 11),
(5, 12),
(5, 18),
(5, 20),
(5, 23),
(5, 24),
(5, 26),
(5, 27),
(5, 28),
(5, 29),
(5, 30),
(5, 31),
(5, 36),
(5, 37),
(5, 38),
(5, 39),
(5, 40),
(5, 43),
(5, 45),
(5, 50),
(5, 51),
(5, 52),
(5, 53),
(6, 10),
(6, 46);

INSERT INTO citeL(citeL_lettre_id, citeL_pers_id) VALUES
(1, 3),
(2, 2),
(3, 1),
(4, 4),
(5, 4),
(6, 2);